### ISSUE TITLE
[Bug] no control over Scorching Stone

### ISSUE THREAD

**Issue by itsdinkd** [ValleyCraft-Dev-Team/valleycraft-old#43]
I was just made aware that this block pretty much instant kills mobs, which goes against my modpacks purpose, and there is no  way to disable this block from generating in the world. I am the developer of AQM2, would really appreciate it if I could request a config entry to disable blocks that kill mobs from ValleyCraft as I love your mod and do notwant to remove it from the pack

**Comment by l1nkl3** [comment]
absolutely, we'll include it in 2.2 which is releasing in a few days :)

**Comment by l1nkl3** [comment]
wait, just checking, you mean scalding stone, yes? those operate identically to magma, so they shouldn't be killing monsters instantly, thats an odd issue we'll have to look into as well

**Comment by l1nkl3** [comment]
just want to check on a few things, our block is called scalding stone and acts identically to magma, which isnt instantaneous, and we have a config option to prevent them from generating coming in 2.2. we can add another config to prevent them from damaging hostile mobs, but i don't believe the block you're having issues with is ours based on the sounds of it. can you please provide more info?

**Comment by itsdinkd** [comment]
It was scalding stone. Though you might be right, it didn't instantly kill. Apparently the person I saw this happen with had a hidden block that killed in a area. 

Still though, a config option that you mentioned that allows disabling and the option to harm or not would be great

**Comment by AndEditor7** [comment]
We have implemented a config option to disable the harm to mobs. And also, the 2.2 update is now released and available on CurseForge.
