### ISSUE TITLE
Suggestion: Oxidized copper chains

### ISSUE THREAD

**Issue by Qendolin** [ValleyCraft-Dev-Team/valleycraft-old#45]
Because it looks cool

**Comment by AndEditor7** [comment]
I'll implement it when one of our artists is available to make the textures. I'm terrible at doing textures, and I don't want to tempt it.

**Comment by AndEditor7** [comment]
Oxidizable copper chain is now implemented https://github.com/ValleyCraft-Dev-Team/ValleyCraft/commit/644e2317852db03156bca004f69022530c45ccd0

**Comment by Qendolin** [comment]
Can I have a jar? I want to update ConnectibleChains and would like to include support for the upcoming chain types.

**Comment by AndEditor7** [comment]
Here's the jar file~: [valleycraft.jar](https://cdn.discordapp.com/attachments/895769912277078096/939276518721478766/valley-craft-2.2.2-1.18.1.jar)
