### ISSUE TITLE
Just some error, not gamecrashing

### ISSUE THREAD

**Issue by TheButterbrotMan** [ValleyCraft-Dev-Team/valleycraft-old#51]
https://bytebin.lucko.me/AWSXPSAOZv

**Comment by nihalantiir** [comment]
It causes me to be unable to load the world...

**Comment by AndEditor7** [comment]
@InsaanNotFound Do you have a log? Usually latest.log?

**Comment by nihalantiir** [comment]
I've managed to solve this, for me it was badly loaded datapack modifying tags (including rice) with KubeJS. Got it to work back again

**Comment by AndEditor7** [comment]
This issue has been fixed.
