### ISSUE TITLE
Advancements Tab Background Broken

### ISSUE THREAD

**Issue by UncleArya** [ValleyCraft-Dev-Team/valleycraft-old#53]
Hey there. Just added ValleyCraft to Better Minecraft 1.18.1 [Fabric] and the Advancements tab for ValleyCraft has a broken texture for a background. Where might I find the JSON to try fixing this?
Thank you!
![image](https://user-images.githubusercontent.com/100550741/155923551-638507e9-f1da-40ce-b048-072c54fd21ff.png)

**Comment by AndEditor7** [comment]
c4f54d1 - this is where you fix this. It's in `data/valley/advancements/exploration/root.json`
