### ISSUE TITLE
Error Creating Single Player World

### ISSUE THREAD

**Issue by Silverbolt666** [ValleyCraft-Dev-Team/valleycraft-old#62]
Hello,

When creating a new world the game shows the following message:

_"Errors in currently selected datapacks prevented the world from loading. 
You can either try to load it with the vanilla data pack ("safe mode"), or go back to the tittle screeen and fix it manually."_

Pressing on option _"safe mode"_ does not make the game react.

Anexed is the latest log.

Fabric version: 0.14.5
Mod version: valley-craft-2.3-1.18.2.jar
Number of mods on modpack: 106

If more information is needed please say :)

Sorry for the inconvenience

**Edit:** After testing the mod in an instance of its own, the error message still shows.

[latest.log](https://github.com/ValleyCraft-Dev-Team/ValleyCraft/files/8862501/latest.log)

**Comment by AndEditor7** [comment]
It's now fixed in the latest update.
